# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/tfstate-lookup/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
checksum:
  name_template: "checksums.txt"
release:
  use_existing_draft: true
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
